# packages in environment at /home/nfcontrol/miniconda3/envs/st:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.10                   py27_0    anaconda
args                      0.1.0                    pypi_0    pypi
asn1crypto                0.24.0                   pypi_0    pypi
astroid                   1.5.3                    py27_0    anaconda
babel                     2.5.0                    py27_0    anaconda
backports                 1.0                      py27_1    anaconda
backports-csv             1.0.7                    pypi_0    pypi
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                      py27_0    anaconda
blas                      1.0                         mkl    anaconda
bleach                    2.1.3                      py_0    conda-forge
ca-certificates           2019.10.16                    0  
cairo                     1.12.18                       6    anaconda
certifi                   2019.9.11                py27_0  
cffi                      1.11.5           py27h5e8e0c9_1    conda-forge
chardet                   3.0.4                    py27_0    anaconda
clint                     0.5.1                    pypi_0    pypi
configobj                 5.0.6                    py27_0    anaconda
configparser              3.5.0                    py27_0    anaconda
contextlib2               0.5.5                    pypi_0    pypi
cycler                    0.10.0                   py27_0    anaconda
cython                    0.28.5           py27hf484d3e_0  
dbus                      1.10.20                       0    anaconda
decorator                 4.2.1                    py27_0    anaconda
defusedxml                0.6.0                      py_0  
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.14                     py27_0    anaconda
entrypoints               0.2.3                    py27_1    conda-forge
enum34                    1.1.6                    py27_1    anaconda
et_xmlfile                1.0.1                    py27_0    anaconda
expat                     2.1.0                         0    anaconda
fontconfig                2.11.1                        6    anaconda
freeglut                  2.8.1                         0    anaconda
freetype                  2.5.5                         2    anaconda
functools32               3.2.3.2                  py27_2    conda-forge
functools_lru_cache       1.4                      py27_0    anaconda
future                    0.16.0                   py27_1    anaconda
futures                   3.2.0                    py27_0    anaconda
gevent                    1.2.2                    py27_0    anaconda
glib                      2.56.1               h000015b_0    anaconda
gmp                       6.1.2                         0    conda-forge
greenlet                  0.4.12                   py27_0    anaconda
gst-plugins-base          1.8.0                         0    anaconda
gstreamer                 1.8.0                         0    anaconda
harfbuzz                  0.9.39                        1    anaconda
hdf5                      1.8.17                        2    anaconda
html5lib                  1.0.1                      py_0    anaconda
icu                       54.1                          0    anaconda
imagesize                 0.7.1                    py27_0    anaconda
internetarchive           1.8.5                    pypi_0    pypi
ipdb                      0.12.2                   pypi_0    pypi
ipykernel                 4.8.2                    py27_0    anaconda
ipython                   5.6.0                    py27_0    anaconda
ipython_genutils          0.2.0                    py27_0    anaconda
isort                     4.2.15                   py27_0    anaconda
jbig                      2.1                           0    anaconda
jdcal                     1.3                      py27_0    anaconda
jedi                      0.10.2                   py27_2    anaconda
jinja2                    2.10                     py27_0    anaconda
jpeg                      8d                            2    anaconda
jsonpatch                 1.24                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
jsonschema                2.6.0                    py27_1    conda-forge
jupyter_client            5.2.3                    py27_0    anaconda
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.31.12                  py27_1    conda-forge
jupyterlab_launcher       0.10.5                   py27_0    anaconda
lazy-object-proxy         1.3.1                    py27_0    anaconda
lcms                      1.19                          0    anaconda
libffi                    3.2.1                         1    anaconda
libgcc                    5.2.0                         0    anaconda
libgcc-ng                 7.2.0                hdf63c60_3    anaconda
libgfortran               3.0.0                         1    anaconda
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                         0    conda-forge
libiconv                  1.14                          0    anaconda
libpng                    1.6.30                        1    anaconda
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    anaconda
libtiff                   4.0.6                         2    anaconda
libxcb                    1.12                          1    anaconda
libxml2                   2.9.4                         0    anaconda
libxslt                   1.1.29                        0    anaconda
llvm                      3.3                           0    anaconda
lxml                      3.8.0                    py27_0    anaconda
m2crypto                  0.35.2                   pypi_0    pypi
markupsafe                1.0                      py27_0    anaconda
mesa                      10.5.4                        0    anaconda
mistune                   0.8.3                      py_0    conda-forge
mkl                       2017.0.3                      0    anaconda
msgpack-python            0.4.8                    py27_0    anaconda
nbconvert                 5.6.0                    py27_1  
nbformat                  4.4.0                    py27_0    anaconda
ncurses                   5.9                          10    anaconda
notebook                  5.4.1                    py27_0    anaconda
numexpr                   2.6.2               np111py27_0    anaconda
numpy                     1.16.5                   pypi_0    pypi
numpydoc                  0.7.0                    py27_0    anaconda
openpyxl                  2.4.8                    py27_0    anaconda
openssl                   1.0.2p               h14c3975_0  
pandas                    0.20.1              np111py27_0    anaconda
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.1                    py27_0    anaconda
pango                     1.39.0                        0    anaconda
pathlib2                  2.3.0                    py27_0    anaconda
patsy                     0.4.1                    py27_0    anaconda
pcre                      8.42                 h439df22_0    anaconda
pexpect                   4.4.0                    py27_0    anaconda
pickleshare               0.7.4                    py27_0    anaconda
pil                       1.1.7                    py27_2    anaconda
pillow                    3.4.2                    py27_0    anaconda
pip                       19.3.1                   py27_0  
pixman                    0.32.6                        0    anaconda
prompt_toolkit            1.0.15                   py27_0    anaconda
psutil                    5.2.2                    py27_0    anaconda
psychopy                  1.85.2                   pypi_0    pypi
ptyprocess                0.5.2                    py27_0    anaconda
pycairo                   1.10.0                   py27_0    anaconda
pycodestyle               2.3.1                    py27_0    anaconda
pycparser                 2.19                       py_0    conda-forge
pyflakes                  1.6.0                    py27_0    anaconda
pygame                    1.9.2a0                  py27_0    cogsci
pygle                     0.20                     pypi_0    pypi
pyglet                    1.3.2                    pypi_0    pypi
pygments                  2.2.0                    py27_0    anaconda
pylint                    1.7.2                    py27_0    anaconda
pyopengl                  3.1.1a1             np111py27_0    anaconda
pyosf                     1.0.4                    py27_0    conda-forge
pyparallel                0.2.2                    pypi_0    pypi
pyparsing                 2.2.0                    py27_0    anaconda
pyqt                      4.11.4                   py27_4    anaconda
pytables                  3.3.0               np111py27_0    anaconda
python                    2.7.13                        0    anaconda
python-dateutil           2.7.2                      py_0    conda-forge
pytz                      2017.2                   py27_0    anaconda
pyyaml                    3.12                     py27_0    anaconda
pyzmq                     17.0.0                   py27_4    conda-forge
qt                        4.8.7                         4    anaconda
qtawesome                 0.4.4                    py27_0    anaconda
qtconsole                 4.2.1                    py27_0    anaconda
qtpy                      1.3.1                    py27_0    anaconda
readline                  6.2                           2    anaconda
requests                  2.14.2                   py27_0    anaconda
rope                      0.9.4                    py27_1    anaconda
scandir                   1.7                      py27_0    conda-forge
schema                    0.7.1                    pypi_0    pypi
scipy                     0.19.0              np111py27_0    anaconda
send2trash                1.5.0                      py_0    conda-forge
setuptools                36.4.0                   py27_1    anaconda
simplegeneric             0.8.1                    py27_0    anaconda
singledispatch            3.4.0.3                  py27_0    anaconda
sip                       4.18                     py27_0    anaconda
six                       1.12.0                   pypi_0    pypi
snowballstemmer           1.2.1                    py27_0    anaconda
sphinx                    1.6.3                    pypi_0    pypi
sphinxcontrib             1.0                      py27_0    anaconda
sphinxcontrib-websupport  1.0.1                    py27_0    anaconda
spyder                    3.2.3                    py27_0    anaconda
sqlite                    3.13.0                        0    anaconda
statsmodels               0.8.0               np111py27_0    anaconda
subprocess32              3.2.7                    py27_0    anaconda
system                    5.8                           2    anaconda
terminado                 0.8.1                    py27_0    anaconda
testpath                  0.3.1                    py27_0    anaconda
tk                        8.5.18                        0    anaconda
tornado                   5.0.1                    py27_1    anaconda
total-ordering            0.1.0                    pypi_0    pypi
traitlets                 4.3.2                    py27_0    anaconda
trollius                  2.2.post1                pypi_0    pypi
typing                    3.6.2                    py27_0    anaconda
wcwidth                   0.1.7                    py27_0    anaconda
webencodings              0.5                      py27_0    conda-forge
wheel                     0.29.0                   py27_0    anaconda
wrapt                     1.10.11                  py27_0    anaconda
wxpython                  3.0.0.0                  py27_2    anaconda
xlrd                      1.1.0                    py27_0    anaconda
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.3                         0    anaconda
yaml                      0.1.6                         0    anaconda
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11                        0    anaconda
